# niri configuration, written against the 26.04 schema in nixpkgs 26.05 and
# based on upstream's resources/default-config.kdl.
#
# Covers input, output, layout and compositor keybinds. Shell-dependent parts
# come from config.kalliope.niri.*; see home/shells/default.nix.
{ config, pkgs, lib, ... }:

let
  c = import ../lib/kanagawa-dragon.nix;
  cfg = config.kalliope.niri;

  # spawn-at-startup takes one quoted token per argv element.
  startupLines = lib.concatMapStringsSep "\n"
    (argv: "spawn-at-startup " + lib.concatMapStringsSep " " (a: ''"${a}"'') argv)
    cfg.startup;

  focusRing = lib.optionalString cfg.focusRing ''
    focus-ring {
            width 2
            active-color "${c.accent}"
            inactive-color "${c.inactive}"
        }
  '';
in
{
  home.packages = [ pkgs.xwayland-satellite ];

  # KDL inside a Nix '' string: a literal ${...} must be written ''${...}.
  # The wpctl binds contain @DEFAULT_AUDIO_SINK@ and no ${}, so they need no
  # escaping. Anything added later using shell variable expansion does.
  xdg.configFile."niri/config.kdl".text = ''
    // Generated by home/niri.nix — do not edit in place.
    ${cfg.extraConfig}
    input {
        keyboard {
            xkb { }
            numlock
        }
        touchpad {
            tap
            natural-scroll
            dwt
            accel-profile "adaptive"
        }
        focus-follows-mouse max-scroll-amount="0%"
    }

    // 13.5" 2880x1920 at 252 PPI. scale 1.5 gives a 1920x1280 logical
    // desktop. 2.0 gives 1440x960 and avoids fractional-scaling blur in
    // XWayland clients.
    output "eDP-1" {
        mode "2880x1920@120.000"
        scale 1.5
        variable-refresh-rate
    }

    layout {
        gaps 8
        center-focused-column "never"
        ${focusRing}
        default-column-width { proportion 0.5; }
        preset-column-widths {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }
    }

    prefer-no-csd

    screenshot-path "~/pictures/screenshots/screenshot-%Y-%m-%d-%H-%M-%S.png"

    // The nixpkgs niri module sets enableXWayland = false, so XWayland
    // comes from xwayland-satellite and niri must start it.
    spawn-at-startup "xwayland-satellite"
    ${startupLines}

    environment {
        DISPLAY ":0"
    }

    binds {
        Mod+Shift+Slash { show-hotkey-overlay; }
        Mod+T { spawn "footclient"; }
        Mod+Shift+T { spawn "ghostty"; }

        Mod+Q repeat=false { close-window; }
        Mod+O repeat=false { toggle-overview; }

        Mod+Left  { focus-column-left; }
        Mod+Down  { focus-window-down; }
        Mod+Up    { focus-window-up; }
        Mod+Right { focus-column-right; }
        Mod+H     { focus-column-left; }
        Mod+J     { focus-window-down; }
        Mod+K     { focus-window-up; }
        Mod+L     { focus-column-right; }

        Mod+Ctrl+Left  { move-column-left; }
        Mod+Ctrl+Down  { move-window-down; }
        Mod+Ctrl+Up    { move-window-up; }
        Mod+Ctrl+Right { move-column-right; }

        Mod+Page_Down { focus-workspace-down; }
        Mod+Page_Up   { focus-workspace-up; }
        Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
        Mod+Ctrl+Page_Up   { move-column-to-workspace-up; }

        Mod+R { switch-preset-column-width; }
        Mod+F { maximize-column; }
        Mod+Shift+F { fullscreen-window; }
        Mod+C { center-column; }
        Mod+Minus { set-column-width "-10%"; }
        Mod+Equal { set-column-width "+10%"; }

        Print { screenshot; }
        Ctrl+Print { screenshot-screen; }
        Alt+Print { screenshot-window; }

        Mod+Shift+E { quit; }
        Ctrl+Alt+Delete { quit; }

    ${cfg.binds}
    }
  '';
}
