# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/391d6a72-b917-47d0-bca7-1805c9f4d2be";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/391d6a72-b917-47d0-bca7-1805c9f4d2be";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/391d6a72-b917-47d0-bca7-1805c9f4d2be";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/krater" =
    { device = "/dev/disk/by-uuid/391d6a72-b917-47d0-bca7-1805c9f4d2be";
      fsType = "btrfs";
      options = [ "subvol=@krater" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/391d6a72-b917-47d0-bca7-1805c9f4d2be";
      fsType = "btrfs";
      # nodatacow: avoid btrfs CoW fragmentation on the Postgres cluster
      # files that live here. New files inherit NOCOW from the mount.
      options = [ "subvol=@data" "nodatacow" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F722-64F8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
